[2024-09-10T14:01:46.320+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T14:01:46.333+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: apache_beam_etl_pipeline.run_beam_pipeline1 manual__2024-09-10T08:31:35.381538+00:00 [queued]>
[2024-09-10T14:01:46.339+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: apache_beam_etl_pipeline.run_beam_pipeline1 manual__2024-09-10T08:31:35.381538+00:00 [queued]>
[2024-09-10T14:01:46.340+0530] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-10T14:01:46.355+0530] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_beam_pipeline1> on 2024-09-10 08:31:35.381538+00:00
[2024-09-10T14:01:46.357+0530] {standard_task_runner.py:72} INFO - Started process 173184 to run task
[2024-09-10T14:01:46.360+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'apache_beam_etl_pipeline', 'run_beam_pipeline1', 'manual__2024-09-10T08:31:35.381538+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/aaz.py', '--cfg-path', '/tmp/tmpyn4hqngd']
[2024-09-10T14:01:46.360+0530] {standard_task_runner.py:105} INFO - Job 51: Subtask run_beam_pipeline1
[2024-09-10T14:01:46.398+0530] {task_command.py:467} INFO - Running <TaskInstance: apache_beam_etl_pipeline.run_beam_pipeline1 manual__2024-09-10T08:31:35.381538+00:00 [running]> on host PG0392KD.springernature.com
[2024-09-10T14:01:46.451+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow_SS' AIRFLOW_CTX_DAG_ID='apache_beam_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_beam_pipeline1' AIRFLOW_CTX_EXECUTION_DATE='2024-09-10T08:31:35.381538+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-10T08:31:35.381538+00:00'
[2024-09-10T14:01:46.452+0530] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-10T14:01:46.452+0530] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-10T14:01:46.452+0530] {logging_mixin.py:190} INFO - Current task name:run_beam_pipeline1 state:running start_date:2024-09-10 08:31:46.333756+00:00
[2024-09-10T14:01:46.452+0530] {logging_mixin.py:190} INFO - Dag name:apache_beam_etl_pipeline and current dag run status:running
[2024-09-10T14:01:46.452+0530] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T14:01:46.453+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-10T14:01:46.453+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 etl_pipe_1.py']
[2024-09-10T14:01:46.460+0530] {subprocess.py:86} INFO - Output:
[2024-09-10T14:01:46.468+0530] {subprocess.py:93} INFO - python3: can't open file '/tmp/airflowtmpytw_13p0/etl_pipe_1.py': [Errno 2] No such file or directory
[2024-09-10T14:01:46.470+0530] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-10T14:01:46.475+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-10T14:01:46.483+0530] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-10T14:01:46.483+0530] {logging_mixin.py:190} INFO - Task start:2024-09-10 08:31:46.333756+00:00 end:2024-09-10 08:31:46.483138+00:00 duration:0.149382
[2024-09-10T14:01:46.483+0530] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_beam_pipeline1> dag:<DAG: apache_beam_etl_pipeline> dagrun:<DagRun apache_beam_etl_pipeline @ 2024-09-10 08:31:35.381538+00:00: manual__2024-09-10T08:31:35.381538+00:00, state:running, queued_at: 2024-09-10 08:31:35.467649+00:00. externally triggered: True>
[2024-09-10T14:01:46.484+0530] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2024-09-10T14:01:46.484+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=apache_beam_etl_pipeline, task_id=run_beam_pipeline1, run_id=manual__2024-09-10T08:31:35.381538+00:00, execution_date=20240910T083135, start_date=20240910T083146, end_date=20240910T083146
[2024-09-10T14:01:46.499+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T14:01:46.499+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 51 for task run_beam_pipeline1 (Bash command failed. The command returned a non-zero exit code 2.; 173184)
Traceback (most recent call last):
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sst7260/airflow_projects/project1/env/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-10T14:01:46.534+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-10T14:01:46.549+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T14:01:46.550+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-10T14:01:47.705+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T14:01:47.714+0530] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: apache_beam_etl_pipeline.run_beam_pipeline1 manual__2024-09-10T08:31:35.381538+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-09-10T14:01:47.714+0530] {local_task_job_runner.py:166} INFO - Task is not able to be run
